const focusVideos = [
//Night Focus Jazz: Lo-Fi Grooves for Deep Late Hours 24
"O_DlB-RyU-4",
"Il2V_fgVh0o",
"XPv78upJZhQ",
"iRSTgLr4WVE",
"xRsKQTR_gys",
"JVw2HcG7eYA",
"exObclq2hmc",
"6VMIYwleTt8",
"WZc2WrQDah4",
"gz7g8KsL1-U",
"ThtVg-d_t7A",
"gQ8xMq2sVFU",
"ToDtY3yBLT4",
"Cg1Sfhm6X00",
"ZkADCyVg-0Y",
"Epq7vJtCYFo",
"2TorZk-fHn4",
"gYbalix2UdE",
"LMgKuk73eB0",
"K2mYoY1hOg8",
"92NTO5odzAI",
"m0oqLWYwsoo",
"7tKXmvLxVo4",
"qcsZUe_90Kg",
//Chillhop Lo-Fi Relax & Focus(Instrumental)26曲
"tOQQZ8Y4PiY",
"3B8ZMRUhgz0",
"q2MxqG7PnVU",
"ZlfP3CZezf4",
"vMx0x6AAuGw",
"42cFykviBOw",
"7HWy_a8FKus",
"vIB8IwEx-5M",
"pyimrJmztY4",
"sZma3f22cjU",
"o8pGSjxMbXA",
"QngvThcVLK4",
"MBsx4sUtNxs",
"FcWLb54O-Xo",
"mcBfjz2H2Hg",
"wNF1SogeWzU",
"eDizSujWyqA",
"GnlFdt0Vb14",
"Ys7xsA8F1q4",
"B2z6HCdctE4",
"J_ybJwELfbg",
"kJBJd5ehJmk",
"kvIz-MNneAc",
"O_RLNql0OhI",
"4bnoHteo-lk",
"sb4vo2QPWrg", 
//Midnight Chillhop Jazz Lo-Fi: Smooth Beats for Focus, Relax & Sleep 深夜の作業 26曲
"MuS5-7ddMcc",
"bfBJ0dXM9kc",
"bTVKgfovmC4",
"HH0RgbDzUnA",
"XJzzv5L8PZE",
"ZYgfrenkTCQ",
"MKg_l1dLdPs",
"r4ZR0fhf338",
"UoEhlhFmNvc",
"2OBf4mMCqQw",
"fJSUC2HKDPY",
"FDwd8Zm2xOQ",
"c61EUWcaIgs",
"GLP74q2vBjM",
"yvAHg7sTnzs",
"Y71zP0Kf9AA",
"CW8QHSCRUKI",
"YwjEK3odv8M",
"VB1FePRH1i4",
"0FOxLF1WSEE",
"znDSfosUFIM",
"F-35FnzFclE",
"7CkwOVyq5ys",
"liRkdME-xtk",
"bcuZOTsTkH0",
"YGyDkXeFl4I"
];

const sleepVideos = [
"_5pVC_EikhU",
"I1Z_YHeA-Pc",
"9TdxiCHk2pE",
"ZKToG7LgRng",
"VejgU2bcANk",
"k9ASW7BpFBU",
"2OM843s6zzI",
"tZiYlmaP9tM",
"UoAqGRCQ228",
"OfxWXhRzQhg",
"qjj-puLxAYE",
"GsZKXQwAIsI",
"eHavhbzCNx4",
"J0o8vNHGpX8",
"l63sRbNvWug",
"nMPe3Duu8ZE",
"UTV1uH5lZE8",
"so5sup5qf_Q",
"N87eDWN4pXU",
"L83nUlxwoGQ",
"1iIsvDtlAew",
"3FajVMiuS_4",
"V93swbtmJGA",
"B_SNM3bi4p8",
//Spiritual Healing: Lo-Fi Frequencies for Meditation & Focus
"vLaohDXCp-Y",
"DEPPozz1OAk",
"dSeNrrJYLRg",
"IIAb9gGT9Eo",
"2adjmXwFUhk",
"4KmEhWkQ2ZA",
"9E0rcSBsU8o",
"2WC7ceST-4U",
"lSMo9oT5VVQ",
"21N-_ZF7CQU",
"ARO1oJKiq9Y",
"lrQYaqacWzU",
"qX_p136g0F4",
"_GbCyG6ukjU",
"mgMN9lORQHQ",
"C81_Q6_0CKQ",
"EKPWgN1nHSQ",
"zDriG45v2ac",
"ZrwvQT5-edM",
//Midnight Jazzhop:Lo-Fi Grooves for Late Nights
"bH541iu6IXA",
"7JR6ODaLd-0",
"RUcJ9u41stg",
"xbyhSlooo_Y",
"kzw61bImAMQ",
"DzyPXfucCDI",
"DE4dp0566kU",
"wTRO0Xo0YRM",
"r99wpkeymPk",
"QEAQQZWoBZw",
"X6hF0eDP0zI",
"VePJ0EcIi8M",
"XD75rUFlelo",
"hzrbJNZA_Ss",
"AQkOIdruMBQ",
"wmgbxnNf6io",
"u-Pry8K5XyA",
"Dq7IPnjSzPc",
"sb8X53d893E",
"xrhnDF6WwpE"
];

const tokyoVideos = [
//Tokyo Night Café Lo-Fi Jazzhop: Minami Aoyama Piano Beats 20曲
"rjK5Ql3BaaQ",
"HUiHKaXY1pg",
"xmU7_SAzh8s",
"kcqpYe2ZY80",
"jMXYAg1AtKI",
"cG5m3tGTgvQ",
"cIolr-NRUMc",
"tabA-UHlFhA",
"vGzkMVfSUxU",
"bKMa79xcO2M",
"aa0OiDRkdZQ",
"jANrXnsQFMg",
"f5Z5sYhCqC4",
"XhBMZzUacao",
"_-w74TcD6ko",
"kV4GjsooLoU",
"jJOofeSVC_k",
"QjoJbU04ATs",
"2c39TplP3G0",
"oj2rsPk8oTs",
//Tokyo Lo-Fi Jazzhop Café – Smooth Piano Sessions　20曲
"u9SQYkvl2Co",
"AoTQv875X3I",
"PElA1kOw-pw",
"4mV3W7fxoCc",
"OTujTFF8n7g",
"A_SW-niVN2k",
"LPmdc-JruKo",
"jAF9M7VfPEo",
"Bz5aCH4wLZw",
"BHrEmsb3g24",
"wI3UCxhN3cY",
"R-S9xNdzYNg",
"ginJRnAQutg",
"E8uzi72Xh7g",
"0CP3I02TF4U",
"OP6eLoKHF90",
"rPrkPrFd7XA",
"DylwKutnngI",
"I_-0WehXWDg",
"utDr866BM4w",
"B241rGLSciI",
"U0CpdM_GFG8",
"7qqcm8ZzJks",
"adUad0ncM1s",
"SBkdqPJCmbU",
//Midnight Soulful Lo-Fi Jazzhop: Smooth Sax & Keys for Deep Focus　19曲
"BWJI30hbg5s",
"KkMoWEiQgsU",
"6Ijofdkt5p8",
"UwzEfKSMWnE",
"JgDeLKQuHBs",
"p5KUZ78_A1Y",
"fiyCuyj1Hxw",
"dwIQBY9gMWo",
"gXmICQMFqok",
"v1MVwIq2c9A",
"mQyy9f_791Q",
"GfYvngoCslc",
"75pHsKEbbCk",
"1UrXMR6KfQQ",
"7Px3wvZHwOk",
"Ane2mMWD30M",
"e8BABZDVcNQ",
"4iuspVKPNOs",
"2_9RUds3DA4"
];


// ===== ランダム動画取得（同じ動画が連続しない版） =====
function randomVideo(list, lastVideo = null) {

  let newVideo;

  do {
    newVideo = list[Math.floor(Math.random() * list.length)];
  } while (newVideo === lastVideo);

  return newVideo;
}
