const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');const {loadAlbums}=require('./build-catalog');const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
function dom(){const els={},blobs=[];const el=id=>els[id]??=( {textContent:'',innerHTML:'',style:{},dataset:{},value:['genreFilter','useFilter'].includes(id)?'all':id==='sortOrder'?'featured':'',listeners:{},classList:{add(){},remove(){}},addEventListener(n,f){this.listeners[n]=f},setAttribute(n,v){this[n]=v},removeAttribute(n){delete this[n]},scrollIntoView(){},appendChild(){},remove(){},click(){},select(){}});const c={window:{},console,URLSearchParams,Blob,URL:{createObjectURL(b){blobs.push(b);return 'blob:test'},revokeObjectURL(){}},setTimeout(){},clearTimeout(){},navigator:{clipboard:{async writeText(s){c.copied=s}}},document:{getElementById:el,querySelector:el,querySelectorAll(){return []},createElement:el,body:el('body')}};vm.createContext(c);return {c,el,blobs};}
(async()=>{const albums=loadAlbums();const expected=albums.reduce((n,a)=>n+a.trackCount,0);
for(const a of albums){const html=read('catalog/'+a.pageSlug+'.html');assert(!/@@[A-Z_]+@@/.test(html));const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)];const ld=JSON.parse(scripts[0][1]);assert.equal(ld.numTracks,a.trackCount);assert.equal(ld.name,a.title);ld.track.forEach((t,i)=>{assert.equal(t.name,a.tracks[i].title);assert.equal(t.isrcCode,a.tracks[i].isrc);assert(t.url.endsWith(a.tracks[i].youtubeId));});const {c,el,blobs}=dom();vm.runInContext(read('js/catalog/b2b-core.js'),c);vm.runInContext(read('js/catalog/albums/'+a.slug+'.js'),c);assert.equal(c.window.NanashinoB2B.validate().length,0);vm.runInContext(scripts.at(-1)[1],c);assert.equal(el('resultCount').textContent,`${a.trackCount} of ${a.trackCount} tracks`);
for(let i=0;i<a.tracks.length;i++){vm.runInContext(`setPlayer(${i},false)`,c);assert(el('catalogPlayer').src.includes('/'+a.tracks[i].youtubeId+'?'));assert.equal(el('playerTrackTitle').textContent,a.tracks[i].title);}
const first=a.tracks[0];el('trackSearch').listeners.input({target:{value:first.isrc}});assert.equal(el('resultCount').textContent,`1 of ${a.trackCount} tracks`);await el('trackRows').listeners.click({target:{closest(selector){return selector==='[data-copy]'?{dataset:{copy:first.isrc}}:null}}});assert.equal(c.copied,first.isrc);
el('downloadCsv').listeners.click();const csv=await blobs[0].text();assert.equal(csv.split('\n').length,a.trackCount+1);for(const t of a.tracks)assert(csv.includes('"'+t.title.replaceAll('"','""')+'"'));}
const bundle={window:{},console};vm.runInNewContext(read('js/b2bvideos.js'),bundle);assert.equal(bundle.window.NanashinoB2B.validate().length,0);assert.equal(Object.keys(bundle.window.NanashinoB2B.albums).length,albums.length);
const index=read('catalog/index.html'),{c,el}=dom();const scripts=[...index.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)];assert.equal(JSON.parse(scripts[0][1]).mainEntity.numberOfItems,albums.length);vm.runInContext(scripts.at(-1)[1],c);assert.equal(Number(el('albumTotal').textContent),albums.length);assert.equal(Number(String(el('trackTotal').textContent).replace(/,/g,'')),expected);el('catalogSearch').value=albums.at(-1).distributionUpc;el('catalogSearch').listeners.input();assert.equal(el('resultCount').textContent,`Showing 1 of ${albums.length} albums`);
if(process.argv.includes('--sitemap')){const xml=read('sitemap.xml');for(const a of albums)assert(xml.includes('/catalog/'+a.pageSlug+'.html</loc>'));assert(xml.includes('/catalog/</loc>'));assert(!xml.includes('/_catalog/'));}
console.log(`PASS: ${albums.length} pages, ${expected} preview mappings, search, copy, CSV, JSON-LD, index totals/filter, legacy bundle${process.argv.includes('--sitemap')?', sitemap':''}.`);
})().catch(e=>{console.error(e);process.exit(1)});

